version: '3.8'

services:
  app:
    build: .
    image: temu-order-service:latest
    container_name: temu-order-service
    ports:
      - "8001:8000"
    volumes:
      - ./logs:/app/logs
      - ./output:/app/output
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - temu-network

networks:
  temu-network:
    driver: bridge 