# 数据库连接池配置
pool:
  # 连接池大小
  pool_size: 20
  # 允许的最大连接数超出pool_size的数量
  max_overflow: 10
  # 获取连接的超时时间（秒）
  pool_timeout: 30
  # 连接回收时间（秒）
  pool_recycle: 3600
  # 连接前ping一下数据库，确保连接有效
  pool_pre_ping: true
  # 连接重试次数
  retry_count: 3
  # 重试间隔（秒）
  retry_interval: 1

# 连接参数
connection:
  # 是否启用SSL
  ssl_mode: 'prefer'
  # 连接超时时间（秒）
  connect_timeout: 10
  # 查询超时时间（秒）
  command_timeout: 30
  # 最小连接数
  min_size: 10
  # 最大连接数
  max_size: 30
  # 连接获取超时时间（秒）
  acquire_timeout: 20

# 健康检查配置
health_check:
  # 健康检查间隔（秒）
  interval: 60
  # 健康检查超时时间（秒）
  timeout: 5
  # 连续失败多少次认为连接不健康
  max_failures: 3 